; PlatformIO Project Configuration File
; ESP32 UART Bridge: riceve da UART2 e inoltra via USB-Serial (UART0)

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -O2
    -mlongcalls
    -Wl,-u,setup -Wl,-u,loop
    -DUSE_ARDUINO_FRAMEWORK
    ; --- Configurazione UART bridge ---
    -DUART_BRIDGE_BAUD=115200
    -DUART_BRIDGE_RX_PIN=13
    -DUART_BRIDGE_TX_PIN=14
    -DUART_BRIDGE_PARITY=SERIAL_8N1

build_src_filter = +<*.cpp> +<*.c>
upload_speed = 115200
upload_port = /dev/cu.usbserial-599D0190451
monitor_port = /dev/cu.usbserial-599D0190451
